#!/bin/sh
read k
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/ack.txt $k | z3 -in | grep -v "(error" ; echo ack ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/copy_intro.txt $k | z3 -in | grep -v "(error" ; echo copy_intro ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/e-fact.txt $k | z3 -in | grep -v "(error" ; echo e-fact ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/e-simple.txt $k | z3 -in | grep -v "(error" ; echo e-simple ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/hors.txt $k | z3 -in | grep -v "(error" ; echo hors ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/hrec.txt $k | z3 -in | grep -v "(error" ; echo hrec ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/intro1.txt $k | z3 -in | grep -v "(error" ; echo intro1 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/intro3.txt $k | z3 -in | grep -v "(error" ; echo intro3 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/l-zipmap.txt $k | z3 -in | grep -v "(error" ; echo l-zipmap ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/l-zipunzip.txt $k | z3 -in | grep -v "(error" ; echo l-zipunzip ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/max.txt $k | z3 -in | grep -v "(error" ; echo max ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mc91-e.txt $k | z3 -in | grep -v "(error" ; echo mc91-e ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mc91.txt $k | z3 -in | grep -v "(error" ; echo mc91 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mult-e-m1.txt $k | z3 -in | grep -v "(error" ; echo mult-e-m1 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mult-e-m2.txt $k | z3 -in | grep -v "(error" ; echo mult-e-m2 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mult-e.txt $k | z3 -in | grep -v "(error" ; echo mult-e ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mult-m1.txt $k | z3 -in | grep -v "(error" ; echo mult-m1 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/mult.txt $k | z3 -in | grep -v "(error" ; echo mult ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/repeat-e.txt $k | z3 -in | grep -v "(error" ; echo repeat-e ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/r-lock-e.txt $k | z3 -in | grep -v "(error" ; echo r-lock-e ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/r-lock.txt $k | z3 -in | grep -v "(error" ; echo  r-lock ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/sum-e-m1.txt $k | z3 -in | grep -v "(error" ; echo sum-e-m1 ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/sum-e.txt $k | z3 -in | grep -v "(error" ; echo sum-e ; echo ""
time ./TopLevel.native ../extras/sample_programs/MoCHi_samples/sum.txt $k | z3 -in | grep -v "(error" ; echo sum ; echo ""
